package com.example.Foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ajustes_administrador_ventana extends VerticalLayout {
	protected Button foro_html;
	protected Button notificaciones_html;
	protected Button ajustes_html;
	protected Button cerrarsesion_html;
	protected Button perfil_html;
	protected Button usuarios_html;
	protected Button amigos_html;
	protected Button reportados_html;
	protected Button baneados_html;
	protected Button mensajes_html;
	protected VerticalLayout vista_amigos_html;
	protected VerticalLayout listaamigos_html;
	protected VerticalLayout vista_lista_usuarios_html;
	protected VerticalLayout listausuarios_html;
	protected VerticalLayout vista_mensajes_html;
	protected TextField numeromensajes_html;
	protected Button cambiar_html;
	protected VerticalLayout vista_perfil_html;
	protected Label nombreusuario_html;
	protected Label emailusuario_htmlm;
	protected Label contrasena_html;
	protected Button mcontrasena_html;
	protected Button mperfil_html;
	protected VerticalLayout vista_usuarios_revision_html;
	protected VerticalLayout listausuariosrevision_html;
	protected VerticalLayout vista_usuarios_baneados_html;
	protected VerticalLayout listaususariosbaneados_html;

	public Ajustes_administrador_ventana() {
		Design.read(this);
	}
}
