package com.example.Foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Usuario_ventana extends VerticalLayout {
	protected Button foro_html;
	protected HorizontalLayout partenoregistrado_html;
	protected Button registrarse_html;
	protected Button iniciarsesion_html;
	protected HorizontalLayout parteregistrado_html;
	protected Button notificacion_html;
	protected Button ajustes_html;
	protected Button cerrarsesion_html;
	protected Label nombreusuario_html;
	protected Button amigos_html;
	protected Button perfil_html;
	protected Button mensajes_html;
	protected VerticalLayout vista_mensajes_html;
	protected VerticalLayout listamensajes_html;
	protected VerticalLayout vista_amigos_html;
	protected VerticalLayout listaamigos_html;
	protected VerticalLayout vista_perfil_html;
	protected TextField nombreusuario_html1;
	protected Button reportar_html;
	protected Button banear_html;
	protected Button agregar_html;

	public Usuario_ventana() {
		Design.read(this);
	}
}
