package com.example.Foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ajustes_administrador_mensajes_ventana extends VerticalLayout {
	protected Button foro_html;
	protected Button notificaciones_html;
	protected Button ajustes_html;
	protected Button cerrarsesion_html;
	protected Button perfil_html;
	protected Button usuarios_html;
	protected Button amigos_html;
	protected Button reportados_html;
	protected Button baneados_html;
	protected Button mensajes_html;
	protected TextField numeromensajes_html;
	protected Button cambiar_html;

	public Ajustes_administrador_mensajes_ventana() {
		Design.read(this);
	}
}
