package com.example.Foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Notificaciones_ventana extends VerticalLayout {
	protected Button foro_html;
	protected Button notificaciones_html;
	protected Button ajustes_html;
	protected Button cerrarsesion_html;
	protected Label notificaciones;
	protected VerticalLayout listanotificaciones_html;

	public Notificaciones_ventana() {
		Design.read(this);
	}
}
