package com.example.Foro;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Vista_tema_no_registrado extends VerticalLayout {
	protected Button foro_html;
	protected Button registrarse_html;
	protected Button iniciarsesion_html;
	protected Label titulotema_html;
	protected VerticalLayout comentarios_html;

	public Vista_tema_no_registrado() {
		Design.read(this);
	}
}
